services:
  # Database Service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: udhai
      MYSQL_DATABASE: test_scani5
    volumes:
      - ./backend/docker/mysqldata:/var/lib/mysql
      - ./backend/docker/mysql/createDevDB.sql:/docker-entrypoint-initdb.d/createDevDB.sql
      - ./backend/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - scani5-network

  # Laravel PHP Service
  backend:
    image: scani5_backend
    build:
      context: ./backend
      dockerfile: docker/DockerfilePHP
      args:
        buildno: 1.0
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8038:80"    # Laravel web server
      - "8082:8082"  # Reverb WebSocket server
    depends_on:
      - db
    networks:
      - scani5-network

  # React Frontend Service (Production Build with Nginx)
  frontend:
    image: scani5_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Serves production build on port 3000
    depends_on:
      - backend
    networks:
      - scani5-network

  # Adminer (DB Viewer)
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8039:8080"
    depends_on:
      - db
    networks:
      - scani5-network

# Networks
networks:
  scani5-network:
    driver: bridge
